version: '3'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        depends_on:
            - api-db
            - rabbitmq
        env_file:
            - backend/.env
        volumes:
            - ./backend:/var/www/backend
        environment:
            XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost idekey=IDE_XDEBUG"
            PHP_IDE_CONFIG: "serverName=docker-server"
            DATABASE_URL: "pgsql://symfony:symfony@api-db:5432/db_name"

    backend:
        image: nginx:1.14-alpine
        container_name: backend
        depends_on:
            - php
        env_file:
            - backend/.env
        ports:
            - "8080:80"
        volumes:
            - ./backend/public:/var/www/backend/public:ro
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    api-db:
        image: postgres:11-alpine
        container_name: api-db
        environment:
            - DB_HOST=postgres
            - POSTGRES_DB=db_name
            - POSTGRES_USER=symfony
            - POSTGRES_PASSWORD=symfony
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    maildev:
        container_name: maildevt3
        command: --web 80 --smtp 25 --hide-extensions STARTTLS
        image: djfarrelly/maildev
        ports:
            - 8003:80
volumes:
    db-data: {}
